const MEALS = Object.freeze([
  {
    name: "Greek Yogurt Bowl",
    description: "Greek yogurt with mixed berries and honey",
    calories: 320,
    protein: 25,
    carbs: 40,
    fat: 6,
    allergens: ["dairy"],
  },
  {
    name: "Avocado Toast",
    description: "Whole grain toast with mashed avocado and a poached egg",
    calories: 420,
    protein: 18,
    carbs: 45,
    fat: 22,
    allergens: ["egg"],
  },
  {
    name: "Protein Oatmeal",
    description: "Overnight oats with whey protein and banana",
    calories: 450,
    protein: 30,
    carbs: 55,
    fat: 12,
    allergens: ["dairy", "gluten"],
  },
  {
    name: "Spinach Berry Smoothie",
    description: "Blended spinach, banana, berries, and almond milk protein",
    calories: 310,
    protein: 22,
    carbs: 38,
    fat: 10,
    allergens: ["nuts"],
  },
  {
    name: "Chicken Salad Bowl",
    description: "Grilled chicken with mixed greens, quinoa, and vinaigrette",
    calories: 480,
    protein: 35,
    carbs: 35,
    fat: 18,
    allergens: ["none"],
  },
  {
    name: "Turkey Wrap",
    description: "Whole wheat wrap with turkey, lettuce, tomato, and hummus",
    calories: 410,
    protein: 28,
    carbs: 42,
    fat: 14,
    allergens: ["gluten"],
  },
  {
    name: "Salmon with Vegetables",
    description: "Baked salmon with roasted vegetables and brown rice",
    calories: 520,
    protein: 38,
    carbs: 45,
    fat: 16,
    allergens: ["fish"],
  },
  {
    name: "Tofu Stir Fry",
    description: "Firm tofu with mixed vegetables and jasmine rice",
    calories: 430,
    protein: 22,
    carbs: 55,
    fat: 12,
    allergens: ["soy"],
  },
  {
    name: "Protein Pancakes",
    description: "Pancakes made with protein powder and topped with fresh fruit",
    calories: 380,
    protein: 28,
    carbs: 48,
    fat: 10,
    allergens: ["dairy", "egg", "gluten"],
  },
  {
    name: "Beef and Vegetable Bowl",
    description: "Lean beef with roasted vegetables and sweet potato",
    calories: 500,
    protein: 36,
    carbs: 42,
    fat: 18,
    allergens: ["none"],
  },
  {
    name: "Tuna Salad",
    description: "Canned tuna with vegetables and olive oil dressing",
    calories: 310,
    protein: 28,
    carbs: 12,
    fat: 16,
    allergens: ["fish"],
  },
  {
    name: "Egg Fried Rice",
    description: "Brown rice fried with eggs, vegetables, and tamari",
    calories: 440,
    protein: 18,
    carbs: 58,
    fat: 14,
    allergens: ["egg", "soy", "gluten"],
  },
  {
    name: "Grilled Chicken Breast",
    description: "Seasoned chicken breast with steamed broccoli and quinoa",
    calories: 460,
    protein: 42,
    carbs: 38,
    fat: 12,
    allergens: ["none"],
  },
  {
    name: "Lentil Curry",
    description: "Red lentils in coconut curry sauce with basmati rice",
    calories: 420,
    protein: 16,
    carbs: 62,
    fat: 12,
    allergens: ["soy", "coconut"],
  },
  {
    name: "Shrimp and Vegetable Stir Fry",
    description: "Shrimp with mixed vegetables and rice noodles",
    calories: 390,
    protein: 28,
    carbs: 44,
    fat: 10,
    allergens: ["shellfish"],
  },
]);

const MEAL_TIMINGS = Object.freeze(["breakfast", "lunch", "dinner", "snack"]);

module.exports = { MEALS, MEAL_TIMINGS };
